import os
import sys
import pandas as pd
import numpy as np
import joblib
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dotenv import load_dotenv

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from infra_data.storage import DataStorage
from features.enhanced_factors import calculate_all_enhanced_features
from processing.cleaner import filter_stock_codes
from processing.merger import merge_dataframes

load_dotenv()

def send_email(subject, body):
    sender_email = os.getenv("SMTP_USER")
    receiver_email = os.getenv("RECEIVER_EMAIL")
    password = os.getenv("SMTP_PASSWORD")
    smtp_server = os.getenv("SMTP_SERVER", "smtp.qq.com")
    smtp_port = int(os.getenv("SMTP_PORT", "465"))

    if not all([sender_email, receiver_email, password]):
        print("Error: SMTP configuration missing in .env")
        return False

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))

    try:
        server = smtplib.SMTP_SSL(smtp_server, smtp_port)
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        print("Email sent successfully!")
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False

def generate_daily_signal():
    print(f"Generating signals for {datetime.now().strftime('%Y-%m-%d')}...")
    
    # 1. Load Model
    if not os.path.exists('latest_model.joblib'):
        print("Error: latest_model.joblib not found. Run backtest first.")
        return
    
    model_data = joblib.load('latest_model.joblib')
    model = model_data['model']
    scaler = model_data['scaler']
    features = model_data['features']
    timing = model_data['timing']
    
    # 2. Load Latest Data (Today)
    storage = DataStorage()
    end_date = datetime.now().strftime('%Y%m%d')
    start_date = (datetime.now() - pd.Timedelta(days=30)).strftime('%Y%m%d') # Load 1 month for features
    
    print("Loading data...")
    daily = storage.load_daily_data(start_date, end_date)
    other = storage.load_daily_basic(start_date, end_date)
    skill = storage.load_technical_factors(start_date, end_date)
    money_flow = storage.load_money_flow(start_date, end_date)
    chip_data = storage.load_chip_data(start_date, end_date)
    
    df = merge_dataframes([daily, other, skill])
    df = filter_stock_codes(df, patterns=['^60', '^00'])
    df = calculate_all_enhanced_features(df, money_flow, chip_data)
    
    latest_date = df['trade_date'].max()
    today_data = df[df['trade_date'] == latest_date].copy()
    
    if today_data.empty:
        print("No data found for today. Market might be closed.")
        return

    # 3. Predict
    X = today_data[features].fillna(0).replace([np.inf, -np.inf], 0)
    X_scaled = scaler.transform(X)
    probs = model.predict_proba(X_scaled)[:, 1]
    today_data['prob'] = probs
    
    # 4. Filter Candidates
    candidates = today_data[today_data['prob'] > 0.60].sort_values('prob', ascending=False).head(5)
    
    # 5. Format Message
    message = f"--- A-Stock Quant Signal Report ({latest_date.strftime('%Y-%m-%d')}) ---\n\n"
    message += f"Model Config: Entry={timing['entry']}, Exit={timing['exit']}\n\n"
    
    if candidates.empty:
        message += "No high-probability signals found today.\n"
    else:
        message += "Suggested Buy Targets for Tomorrow:\n"
        for _, row in candidates.iterrows():
            message += f"- {row['ts_code']} (Score: {row['prob']:.4f}, Close: {row['close']})\n"
        
        message += f"\nNote: Based on optimization, recommended entry at T+1 {timing['entry'].upper()}.\n"
    
    message += "\nReport generated by Antigravity Quant System."
    
    print(message)
    send_email(f"Quant Signal Report - {latest_date.strftime('%Y-%m-%d')}", message)

if __name__ == "__main__":
    generate_daily_signal()
